[tool.poetry]
name = "lab2"
version = "0.1.0"
description = ""
authors = ["Luca Marcellino <s234262@studenti.polito.it>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
